<div class="header">
    <h3 class="logo">Library Search</h3>
    <div class="nav">
        <ul class="nav-list">
            <li id="search"><a href="search.php">Search</a></li>
            <li id="add"><a href="submission.php">Add a Library</a></li>
            <li id="about"><a href="search.php">About</a></li>
            <li id="login"><a href="registration.php">Login</a></li>
        </ul>
    </div>
</div>